// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpbpaonsyfodtteebszv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYnBhb25zeWZvZHR0ZWVic3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjEwNTEsImV4cCI6MjA2NTM5NzA1MX0.4h1ephRvY981xVUQfQx8GFz_G50KN68XFf8EnM_VgUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);